### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by joschi** [paulwellnerbou/java-grok#9]
This project should have a continuous integration pipeline, e. g. on [Travis CI](https://travis-ci.org/), [Circle CI](https://circleci.com/), or any other CI service.

**Comment by joschi** [comment]
If desired, I can provide a pull request for a Travis CI configuration.

**Comment by paulwellnerbou** [comment]
Yes, that would be great, thanks!
I don't really mind which one, Gihub CI, Travis, Circle, Jenkins, ...

**Comment by joschi** [comment]
I think this issue has been made redundant by the upstream project being active again.
